feat & refactor: misc blog leftover tasks
zenithdb/website pull request #18
Opened 2022-02-14 09:34 UTC by k8isdead

**Describe changes**

This PR brings various tasks [from this Notion page](https://www.notion.so/pixelpoint/Blog-leftovers-bb1c6b6dc19e439f9c62243188c8eb5e#3504b1e5232b4644bf08b2218e117723)

**Steps to test**
1. Go to privacy policy page as an example of a static page in this project
2. Confirm everything works and looks as expected

**TODO**

- [ ] Find a way to make embedded twitter card make responsive 
- [ ] Delete all posts before merging PR and leave only one as an example without much content
- [ ] Respond to additional designers and devs comments, if there are any

2022-02-14 11:33 UTC, kelvich commented
@k8isdead @SilencerWeb @lnikell 

Hey! Sorry for breaking deploys for some time. Cloudflare supports only one build command for all of the branches, and with docs it looks like that:
```
gatsby build --prefix-paths; sh ./build_docs.sh
```
so branches without `build_docs.sh` were broken for some time.

Now I've committed that script both to `main` and `new` branches. So deploy should work after the rebase:

```
git fetch -a
git rebase origin/new
git push -f
```

Small overview of docs build is available in readme https://github.com/zenithdb/website/tree/new#documentation I think now you can ignore it totally for gatsby development.

2022-02-14 13:30 UTC, SilencerWeb requested changes

2022-02-14 13:30 UTC, SilencerWeb commented on gatsby-config.js
> +        name: 'posts',
```suggestion
        name: 'static-pages',
```

2022-02-14 13:30 UTC, SilencerWeb commented on gatsby-node.js
> +
```suggestion
async function createStaticPages({ graphql, actions }) {
  const result = await graphql(`
    query staticPageQuery {
      allMdx(filter: { fileAbsolutePath: { regex: "/src/static-pages/" } }) {
        nodes {
          id
          slug
        }
      }
    }
  `);

  if (result.errors) throw new Error(result.errors);

  result.data.allMdx.nodes.forEach(({ id, slug }) => {
    actions.createPage({
      path: `/${slug}`,
      component: path.resolve('./src/templates/static.jsx'),
      context: { id },
    });
  });
}

```

2022-02-14 13:30 UTC, SilencerWeb commented on gatsby-node.js
> +
Also, let's move this function right after `createBlogPosts`

2022-02-14 13:30 UTC, SilencerWeb commented on src/static-pages/privacy-policy.md
> +## Privacy Policy
```suggestion
# Privacy Policy
```

2022-02-14 13:30 UTC, SilencerWeb commented on src/templates/static.jsx
> +      <div className="safe-paddings py-48 3xl:py-44 2xl:py-40 xl:py-32 lg:py-12 md:py-6">
Why do we have this unnecessary wrapper?

2022-02-14 13:30 UTC, SilencerWeb commented on src/templates/static.jsx
> +const StaticPage = ({
```suggestion
const StaticTemplate = ({
```

2022-02-14 13:30 UTC, SilencerWeb commented on src/static-pages/privacy-policy.md
> +title: 'Zenith — Privacy Policy'
![image](https://user-images.githubusercontent.com/20713191/153872684-62cef1e1-e7f1-4b04-8385-ab0593984102.png)

2022-02-14 13:30 UTC, SilencerWeb commented on src/templates/static.jsx
> +      <div className="safe-paddings py-48 3xl:py-44 2xl:py-40 xl:py-32 lg:py-12 md:py-6">
Also, please think about why bottom padding is wrong and what values we should use

2022-02-15 15:17 UTC, SilencerWeb approved these changes

2022-02-15 15:42 UTC, merged